

 class LaserBeam {

    private isActivated: boolean;
    private hitsAsteroid: boolean; 
    private angle: number;
    private position: p5.Vector;
   


    constructor(isActivated: boolean, hitsAsteroid: boolean, angle: number, position: p5.Vector,)
    {
        this.isActivated = isActivated;
        this.hitsAsteroid = hitsAsteroid;
        this.angle = angle;
        this.position = position;


    }

    public update() {
    

    }
    

    public draw() {

        

        
    }

}